import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/toaster';
import Sidebar from './components/sidebar'; // Perbaiki path impor
import Header from './components/header';
import { SidebarProvider } from './contexts/SidebarContext';
import { SidebarToggle } from './components/sidebar-toggle';
import { Suspense } from 'react';

// Font lokal
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

// Metadata default
export const metadata = {
  title: 'OnLasdan',
  description: 'Generated by create next app',
  keywords: 'Next.js, Vercel, Web Application, Analytics, Speed Insights',
  author: 'OnLasdan',
  robots: 'index, follow',
};

export const generateViewport = () => ({
  viewport: 'width=device-width, initial-scale=1',
});

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <meta name='description' content={metadata.description} />
        <meta name='keywords' content={metadata.keywords} />
        <meta name='author' content={metadata.author} />
        <meta name='viewport' content={generateViewport().viewport} />
        <meta name='robots' content={metadata.robots} />
        <title>{metadata.title}</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
            <SidebarProvider>
              <div className='flex h-screen'>
                <Sidebar />
                <div className='flex flex-1 flex-col overflow-hidden'>
                  <Header>
                    <SidebarToggle />
                  </Header>
                  <main className='flex-1 overflow-y-auto overflow-x-hidden bg-background'>
                    <Suspense>{children}</Suspense>
                  </main>
                </div>
              </div>
            </SidebarProvider>
          <Toaster />
        </ThemeProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
