import { Analytics } from '@vercel/analytics/react'; // Impor Analytics
import { SpeedInsights } from '@vercel/speed-insights/next'; // Impor SpeedInsights
import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'OnLasdan',
  description: 'Generated by create next app',
  keywords: 'Next.js, Vercel, Web Application, Analytics, Speed Insights',
  author: 'OnLasdan',
  viewport: 'width=device-width, initial-scale=1',
  robots: 'index, follow',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <meta name='description' content={metadata.description} />
        <meta name='keywords' content={metadata.keywords} />
        <meta name='author' content={metadata.author} />
        <meta name='viewport' content={metadata.viewport} />
        <meta name='robots' content={metadata.robots} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Analytics /> {/* Tambahkan Analytics di sini */}
        <SpeedInsights /> {/* Tambahkan SpeedInsights di sini */}
      </body>
    </html>
  );
}
