export const metadata = {
  title: 'OnLasdan',
  description: 'Generated by create next app',
  keywords: 'Next.js, Vercel, Web Application, Analytics, Speed Insights',
  author: 'OnLasdan',
  robots: 'index, follow',
};

export const generateViewport = () => ({
  viewport: 'width=device-width, initial-scale=1',
});
